refactor: from node to bun and changeset to changelogen and ci/cd pipeline

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -1,5 +1,9 @@
 name: NPM CI
 
+permissions:
+  contents: write
+  pull-requests: write
+
 on:
   push:
     branches:
@@ -7,43 +11,61 @@ on:
 
 jobs:
   build:
+    if: >
+      !(
+        contains(github.event.head_commit.message, 'ci(release):') ||
+        contains(github.event.head_commit.message, '[skip ci]') ||
+        startsWith(github.event.head_commit.message, 'Merge pull request') ||
+        startsWith(github.event.head_commit.message, 'Merge branch')
+      )
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repo
+      - name: 📥 Checkout Repo
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Setup pnpm
-        run: npm i -g pnpm
-
-      - name: Setup Node.js with pnpm
-        uses: actions/setup-node@v4
+      - name: 🛠️ Setup Bun
+        uses: oven-sh/setup-bun@v2
         with:
-          node-version: lts/*
-          cache: 'pnpm'
+          bun-version: latest
 
-      - name: Install Dependencies
+      - name: 📦 Install Dependencies
+        run: bun install --frozen-lockfile
+
+      - name: ⚙️ Build Artifacts
+        run: bun run build
+
+      # - name: ✅ Test Code
+      #   run: bun run test
+
+      - name: 🧹 Lint Code
+        run: bun run lint || echo "Linting failed, but continuing"
+
+      - name: 🧼 Format Code
+        run: bun run format
+
+      - name: 🤖 AutoFix Code
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: 'chore: apply code fixes [skip ci]'
+
+      - name: 🏷️ Bump Version
+        id: bump_version
         run: |
-          sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev
-          pnpm install
+          rm -f CHANGELOG.md
+          bunx changelogen@latest --bump
+          CHLOG=$(cat CHANGELOG.md)
+          echo -e "CHANGELOG_CONTENT<<EOF\n${CHLOG}\nEOF" >> $GITHUB_ENV
+          git reset --hard
+          bunx changelogen@latest --bump
 
-      - name: Bulid Artifacts
-        run: pnpm build
-
-      # - name: Run Tests
-      #   run: pnpm test
-
-      - name: Lint Code
-        run: pnpm lint || echo "Linting failed, but continuing"
-
-      # - name: Format Code
-      #   run: pnpm format
-
-      - name: Create Release Pull Request
-        uses: changesets/action@v1
+      - name: 🔀 Create or Update Pull Request
+        uses: peter-evans/create-pull-request@v7
         with:
-          title: 'chore(release): update version'
-          commit: 'chore(release): update version'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          commit-message: 'ci(release): update version'
+          title: 'ci(release): update version'
+          body: ${{ env.CHANGELOG_CONTENT }}
+          branch: 'release/update-version'
+          base: 'develop'
+          delete-branch: true
